### ISSUE TITLE
v0.10.0 much slower when using higher number of threads

### ISSUE THREAD

**Issue by sentausa** [StevenWingett/FastQ-Screen#29] opened 2020-08-19 11:19 UTC
Hi,

I'm using FastQ-Screen version 0.10.0 and I found that using 48 threads took seven times longer than using 8 thread for the same data (41 million pairs of 125 bp read). I wonder if it is expected or if this issue is already tackled in the later versions.

By the way, I used bowtie2 v2.3.4.1 when using 48 threads and v2.3.0 when using 8 threads.

Thank you for any clue.

E.

**Comment by StevenWingett** [comment] 2020-08-19 17:00
Thanks for your comment.  

It is difficult to know the cause.  Would you be able to try again at some point, but using the same version of Bowtie for the comparison - it could be a difference in the aligner that is responsible for the different run times.  Also, you will need to process the same FASTQ file for a fair comparison.

Please do use the latest version of FastQ Screen for the comparison, running on the same machine with the same parameters.

Thank you.

**Comment by StevenWingett** [comment] 2022-01-14 15:04
I am unsure whether the comparison was tried, so will close the issue.

**Closed by StevenWingett** 2022-01-14 15:04 UTC
